import "./globals.css";
import Theme from "./Theme/Font"; 
import Headers from "./components/header/Header";
import Footer from "./components/footer/Footer";
import ProfileCard from "./components/footerme/Footerme";
export const metadata = {
  title: "Pixgrow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ overflowX: "hidden" }}>
      <head>
        <link rel="icon" href="/images/favicon.svg" />
      </head>
      <body style={{ backgroundColor: "#eaeaf3", overflowX: "hidden" }}>
        <Theme>
          <Headers />
          {children}
          <Footer />
          <ProfileCard/>
        </Theme>
      </body>
    </html>
  );
}
